backend:
  name: git-gateway
  branch: master

media_folder: /static/images
public_folder: /images

collections:
  #
  # GENERAL PAGES #######################################################
  #
  - label: 'Home Page'
    name: 'home'
    format: 'json'
    delete: false
    files:
      - label: 'Home'
        name: 'home'
        file: 'resources/nuxt/assets/content/index.json'
        fields:
          - { label: 'Intro', name: 'intro', widget: 'string' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
          - { label: 'Link_1', name: 'link_1', widget: 'string' }
          - { label: 'Link_2', name: 'link_2', widget: 'string' }
  - label: 'About Page'
    name: 'about'
    format: 'json'
    delete: false
    files:
      - label: 'About'
        name: 'about'
        file: 'resources/nuxt/assets/content/about.json'
        fields:
          - { label: 'Intro', name: 'intro', widget: 'string' }
          - { label: 'Subtitle', name: 'subtitle', widget: 'markdown' }
          - { label: 'Content_1', name: 'content_1', widget: 'markdown' }
          - { label: 'Content_2', name: 'content_2', widget: 'markdown' }
  - label: "Dreams"
    name: "pages"
    format: 'json'
    files:
      - label: "Dream Entry"
        name: "dreams"
        file: 'resources/nuxt/assets/content/dreams.json'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Type, name: type, widget: string}
          - label: Entry
            name: entry
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Subtitle', name: 'subtitle', widget: 'string' }
              - { label: 'Content', name: 'content', widget: 'markdown' } 
              - { label: 'Author', name: 'author', widget: 'string' }         

    